---
sb_debian_base_admin_user_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjsmczXbTcGnUoR1AllzKc6K1gxINidC8r7wkK6n6RozUcjDM9+MH71w15uHKEAguvzATEjFP9PFOPTcYOpBV1J8WqqStKi52h/JluCDLT/ksn6LMiLdM+Xh7VHl78EgvadPAvCCyoKRmZr/8KQdPtpImSKOecwfGKJegYLjSksXTSjPbe084/L1JrqxHM3O3hJBXSdPAKZJKMOaqc7bRceDibDlvdXyaMZ5I13o5dYX3HAQZfqAGZRgUFN6qsiVX4O4Qt2m8BnvFZXKkbKzs8WduxDqXo6wP6AN68nNjlWq5W8hIyNSTYAg4ip5nA2W5BLhL95v2ZcV0OwzlRauex nvivar@stackbuilders.com

deploy_machine_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+n4mJbV+P9GN2ajZVhzTEJ23FvVLOL/IBcdw/xOAPvrLXpKP7yDPN08SNcQ2XdUkwHfwhtSJP2ARPhrKHsL/aOVWJaBfnHyaBV0N+LLty6ZvS9k2oGVxhiKGwyiVw3cMxhIIAE6eR2+2JF/ZkLVw0uXiJ65JSPcXVPTLqBNKbk53aSpnC36wq9HZDQxE1m3D3n0hBxWEQDSmKgy0But8Y+8zgGRmwr2uzYgUpsmzPDb/i11kxSioOZfTQ5cAnNsKEEyfkVCkcdml7Xm88W/QvyQWHJAO7ftx4890/jLkfBekJwpNbVtQREagVUNGHs7FqZRR9Ku4UPdO/v2Td54wr CircleCI

sb_debian_base_deploy_user_authorized_keys: '{{ sb_debian_base_admin_user_authorized_keys + deploy_machine_keys }}'
